"""Definition of the Plan dataclass.

This module provides the dataclass container representing the ordered recipe
sequence of steps generated by the planning layer.
"""

from dataclasses import dataclass, field
from typing import Any

from argos.intent import Intent
from argos.planning.constants import DEFAULT_PLANNING_ENGINE
from argos.planning.plan_step import PlanStep


@dataclass(slots=True)
class Plan:
    """Represents a structured sequence of actions (plan).

    Attributes:
        steps: The ordered list of plan steps to execute.
        primary_intent: The primary classified intent this plan resolves.
        confidence: The confidence score associated with the classification.
        requires_confirmation: If True, indicates execution requires
            explicit user consent.
        planning_engine: Telemetry tracking identifier for the planner engine.
        metadata: Context diagnostic details.
    """

    steps: list[PlanStep] = field(default_factory=list)
    primary_intent: Intent = Intent.UNKNOWN
    confidence: float = 0.0
    requires_confirmation: bool = False
    planning_engine: str = DEFAULT_PLANNING_ENGINE
    metadata: dict[str, Any] = field(default_factory=dict)
